version: '3'

services:
  pihole:
    image: pihole/pihole:latest
    environment:
      - ServerIP=0.0.0.0
      - WEBPASSWORD=admin123
      - DNS1=1.1.1.1
      - DNS2=1.0.0.1
    ports:
      - "80:80"
      - "53:53"
    volumes:
      - "./pihole:/etc/pihole"
    restart: always
